name: progress

on: push

jobs:
  Progress:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: print dbg message
        run: .github/workflows/progress.sh
        shell: bash
