name: progressupdate

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  Progress:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get progress
        run: |
          python3 ./.github/workflows/progress.py
        shell: bash

      - name: push to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4 # peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build
          # publish_dir: ./build
