name: progressupdate

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  Progress:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get progress
        run: |
          python3 ./.github/workflows/progress.py
        shell: bash

      - name: push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_dir: ./build
          allow_empty_commit: true
