name: progress

on: push

jobs:
  Progress:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: print dbg message
        run: |
          ls -la ./.github/workflows/
          source ./.github/workflows/progress.sh
        shell: bash
