name: progress

on: push

jobs:
  Progress:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: print dbg message
        run: ls -la ./.github/workflows/
        run: source ./.github/workflows/progress.sh
        shell: bash
