name: progress

on:
  push:
    branches:
      - master

jobs:
  Progress:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: true
        matrix:
          version:
            - 1
          arch:
            - x64
          os:
            - ubuntu-latest
      steps:
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
        run: ./progress.sh
