name: progress

on: push

jobs:
  Progress:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: get progress
        run: |
          python3 ./.github/workflows/progress.py
        shell: bash
